version: '3'
services:
  storage:
    image: "arafato/azurite:latest"
    ports:
     - "9569:10000"
     - "9570:10001"
     - "9571:10002"
  functions:
    build: "${FUNCTIONFOLDER}"
    image: "azure-functions-image"
    ports:
     - "9574:80"
  api-app:
    build: "${APIFOLDER}"
    image: "azure-api-app-image"
    ports: 
     - "9567:9000"
  cli:
    image: "microsoft/azure-cli"
  sql-server:
    image: "mysql/mysql-server"
    ports:
      - "3306:3306"
      - "33060:33060"
  keyvault:
      image: vault
      volumes:
        - $PWD/src/services/azure-keyvault/example:/tmp/example/
        - $PWD/src/services/azure-keyvault/logs:/tmp/logs/
      command: server -config /tmp/example/config.hcl
      ports:
        - "8200:8200"
  # Uncomment if your using windows OS 
  # cosmosdb:
  #   env_file: 
  #    - ./compose.env
  #   build: ${COSMOSFOLDER}
  #   image: "azure-cosmosdb-image"
  #   ports:
  #     - "9500:8081"
  #     - "9502:10250"
  #     - "9503:10251"
  #     - "9504:10252"
  #     - "9505:10253"
  #     - "9506:10254"