version: '3'
services:
  storage:
    image: "arafato/azurite:latest"
    ports:
     - "9569:10000"
     - "9570:10001"
     - "9571:10002"
  functions:
    # image: "microsoft/azure-functions-node8:latest"
    image: "azurefunctiondemo"
    ports:
     - "9574:80"
